# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureDevOps Project ARM Connection'
    subscriptionId: 'c9a9de7f-66c5-4ffa-bc73-29f50759e666'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Arm DevOps RG'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/MainTemplate.json'
    overrideParameters: '-projectName AzureDevOps -linkedTemplateUri https://raw.githubusercontent.com/susvin81/ARMPipeline/master/CreateWebApp/LinkedTemplate.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployAzureDevOpsTemplate'
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
